#!/bin/bash
set -e

# check to see if we are using a full-featured gitflow repo
if git show-ref --quiet refs/heads/develop; then
   masterBranch="develop"
else
   masterBranch="master"
fi

((!$#)) && echo No feature name, command ignored! && echo "  - git feature <name>" && exit 1

if [[ "$1" = "--h" ]] ; then
   echo "Creates a feature branch at the latest commit on $masterBranch and checks it out.";
   echo "Feature branches will create a pull request to $masterBranch when finished."
   echo "  - git feature <name>";
   exit 1;
fi

if ! [ -d .git ] ; then
	if ! [ $(git rev-parse --is-inside-work-tree &>/dev/null; echo "${?}") == '0' ] ; then
		echo "Current directory is not a git folder."
		exit 1;
	fi
fi


if git show-ref --quiet refs/heads/feature/$1; then
  echo Switching to existing feature $1
  git checkout feature/$1
else
  echo Starting feature $1
  git checkout -b feature/$1 $masterBranch
fi
